version: "3.8"

services:
  app:
    container_name: node_prisma_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mongo:
        condition: service_healthy
    command: sh -c "npx prisma generate && node src/index.js"
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:7.0
    container_name: mongo_db_prisma
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - mongo_data:/data/db
    entrypoint: >
      bash -c "
      openssl rand -base64 756 > /data/replica.key &&
      chmod 400 /data/replica.key &&
      chown mongodb:mongodb /data/replica.key &&
      exec docker-entrypoint.sh mongod --replSet rs0 --keyFile /data/replica.key --bind_ip_all
      "
    healthcheck:
      test: 
        - "CMD" 
        - "mongosh" 
        - "-u" 
        - "${DATABASE_USER}" 
        - "-p" 
        - "${DATABASE_PASSWORD}" 
        - "--eval" 
        - "try { rs.status() } catch (e) { rs.initiate({_id:'rs0', members:[{_id:0, host:'mongo:27017'}]}) }"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data: